language: c
compiler:
- gcc

before-install:
- sudo apt-get update
install:
- sudo apt-get install build-essential libssl-dev flex libperl-dev bison gettext git-core
script: 
  - git submodule update --init
  - ./configure
  - make
  - make install

notifications:
  irc: "irc.chatfreedom.us#shaleservices"
